In [1]:
import numpy as np
import pandas as pd

path = 'custChurn.csv'
df = pd.read_csv(path)

In [2]:
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

### Analyzing data

In [3]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [4]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [5]:
df.drop(columns=['customerID'], inplace=True)

In [6]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
# TotalCharges is str type, with blank places, so fixing that:

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [8]:
df['TotalCharges'].dtype

dtype('float64')

In [9]:
df['TotalCharges'].isnull().sum()

np.int64(11)

there are still 11 missing values, but a good approach is to fill it with mean/median of the training set after the train/test split.

#### Converting Churn column to 1s and 0s:
- 1: Churned (YES)
- 2: Not churned (NO)

In [10]:
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

In [11]:
df['Churn'].head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

#### Encoding the other columns

In [12]:
binary_cols = [
    "Partner", "Dependents", "PhoneService", "PaperlessBilling"
]

for col in binary_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

In [13]:
df[binary_cols]

      Partner  Dependents  PhoneService  PaperlessBilling
0           1           0             0                 1
1           0           0             1                 0
2           0           0             1                 1
3           0           0             0                 0
4           0           0             1                 1
...       ...         ...           ...               ...
7038        1           1             1                 1
7039        1           1             1                 1
7040        1           1             0                 1
7041        1           0             1                 1
7042        0           0             1                 1

[7043 rows x 4 columns]

In [14]:
df['PaymentMethod'].value_counts()

PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

In [15]:
df['OnlineSecurity'].value_counts()

OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

In [16]:
df['InternetService'].value_counts()

InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

In [17]:
df['gender'] = df['gender'].map({'Male': 0, 'Female': 1})

In [18]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1,0,1,0,1,0,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,1,Electronic check,29.85,29.85,0
1,0,0,0,0,34,1,No,DSL,Yes,No,Yes,No,No,No,One year,0,Mailed check,56.95,1889.50,0
2,0,0,0,0,2,1,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,1,Mailed check,53.85,108.15,1
3,0,0,0,0,45,0,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,0,Bank transfer (automatic),42.30,1840.75,0
4,1,0,0,0,2,1,No,Fiber optic,No,No,No,No,No,No,Month-to-month,1,Electronic check,70.70,151.65,1

In [19]:
df.shape

(7043, 20)

#### Splitting data

In [20]:
X = df.drop('Churn', axis=1)
y = df['Churn']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y)

#### the stratify parameter ensures that the training and testing datasets maintain the same proportion of class labels as the original dataset

In [21]:
median = X_train['TotalCharges'].median()

X_train['TotalCharges'] = X_train['TotalCharges'].fillna(median)
X_test['TotalCharges'] = X_test['TotalCharges'].fillna(median)

Only using the median from the train set, we don't use information from the test set

### SMOTE

The dataset is imbalanced, favouring the non-churn customers

In [22]:
df['Churn'].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

As we can see,
- ~5000 non-churn customers
- ~2000 churning customers

But in reality we care for our churning customers. A model should predict which customers have a tendency to churn, so that loss can be prevented.<br>

Training on this dataset will give a model that will just classify maximum customers to be churning and give accuracy around 75%

### SMOTE: Synthetic Minority Over-sampling Technique
SMOTE creates new synthetic minority examples, and training the model on this would give a better performance<br>

Suppose there are two minority-class customers:<br>
A = [10, 50]
B = [20, 70]<br>

SMOTE can create a new customer somewhere between them.<br>
[10, 50] ─────────── [13, 56] ─────────── [20, 70] ([13, 56] created by some mathematical formula)

#### **FOR DATASETS CONTAINING BOTH NUMERICAL AND CATEGORICAL DATA WE USE** ***SMOTENC***

In [23]:
X_train

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
6661,1,0,1,1,72,0,No phone service,DSL,No,Yes,No,Yes,Yes,Yes,Two year,0,Credit card (automatic),53.65,3784.00
4811,1,0,0,0,4,1,No,DSL,No,No,No,No,No,No,Month-to-month,1,Mailed check,46.00,193.60
2193,0,0,0,1,56,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,1,Mailed check,21.20,1238.65
1904,0,0,0,0,56,1,Yes,Fiber optic,No,Yes,No,Yes,No,Yes,Month-to-month,1,Electronic check,94.45,5124.60
6667,1,0,0,0,9,1,No,Fiber optic,No,No,No,No,No,Yes,Month-to-month,1,Electronic check,79.55,723.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4250,0,0,0,0,63,1,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,No,One year,0,Credit card (automatic),104.50,6590.80
1488,0,0,0,0,1,1,No,DSL,Yes,No,No,No,No,No,Month-to-month,0,Mailed check,51.25,51.25
6303,1,0,1,0,71,1,Yes,Fiber optic,No,Yes,Yes,Yes,Yes,Yes,Two year,0,Electronic check,109.25,7707.70
2710,1,0,1,0,24,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,0,Credit card (automatic),20.40,482.80
5639,0,0,0,0,6,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,0,Mailed check,20.65,109.30

                    DATA
                      │
              Basic cleaning
                      │
                train/test split
                      │
             ┌────────┴────────┐
             │                 │
          TRAIN              TEST
             │                 │
       impute missing       same imputer
             │                 │
       scale numerical     same scaler
             │
          SMOTENC
             │
          OHE
             │
          MODEL
                               │
                         OHE/transform
                               │
                         PREDICTIONS

In [24]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [25]:
numerical_cols = [
    "tenure",
    "MonthlyCharges",
    "TotalCharges"
]

In [26]:
categorical_cols = [
    "gender",
    "SeniorCitizen",
    "Partner",
    "Dependents",
    "PhoneService",
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaperlessBilling",
    "PaymentMethod"
]

In [27]:
df['TotalCharges'].dtype

dtype('float64')

In [28]:
df['TotalCharges'].isnull().sum()

np.int64(11)

The below cell is basically to tell the smotenc model that which cols are categorical and which are not

In [29]:
categorical_indices = [
    X_train.columns.get_loc(col) for col in categorical_cols
]

Before applying smotenc, we must scale the continuous numerical columns

In [30]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train[numerical_cols])

X_train[numerical_cols] = scaler.transform(X_train[numerical_cols])

X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

In [31]:
categorical_indices = [
    X_train.columns.get_loc(col)
    for col in categorical_cols
]

print(categorical_indices)
print(X_train.columns)

[0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='str')

In [32]:
# before smotenc

print(y_train.value_counts())

Churn
0    3880
1    1402
Name: count, dtype: int64

In [33]:
from imblearn.over_sampling import SMOTENC

smotenc = SMOTENC(
    categorical_features=categorical_indices,
    random_state=42
)

X_train_resampled, y_train_resampled = smotenc.fit_resample(
    X_train,
    y_train
)

In [34]:
# after smotenc

print(y_train_resampled.value_counts())

Churn
0    3880
1    3880
Name: count, dtype: int64

In [35]:
X_train_resampled.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,1,0,1,1,1.609608,0,No phone service,DSL,No,Yes,No,Yes,Yes,Yes,Two year,0,Credit card (automatic),-0.371461,0.652432
1,1,0,0,0,-1.151780,1,No,DSL,No,No,No,No,No,No,Month-to-month,1,Mailed check,-0.625032,-0.919905
2,0,0,0,1,0.959870,1,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,1,Mailed check,-1.447065,-0.462248
3,0,0,0,0,0.959870,1,Yes,Fiber optic,No,Yes,No,Yes,No,Yes,Month-to-month,1,Electronic check,0.980917,1.239518
4,1,0,0,0,-0.948737,1,No,Fiber optic,No,No,No,No,No,Yes,Month-to-month,1,Electronic check,0.487034,-0.687890

OHE on the resampled dataset

In [36]:
X_train_resampled = pd.get_dummies(
    X_train_resampled,
    columns=categorical_cols,
    drop_first=True
)

X_test = pd.get_dummies(
    X_test,
    columns=categorical_cols,
    drop_first=True
)

However, the train and test sets might not have the same columns, so fixing that:

This fix is done so that both columns have the same columns, because by chance for e.g. the test set may not have a single credit card customer, that would simply omit the entire `PaymentMethod_Credit_card` column in the test set. That would be problematic.<br>
`fill_value=0` because if the column does not exist, that means there are no credit card customers (0 in OHE terms).

In [37]:
X_train_resampled, X_test = X_train_resampled.align(
    X_test,
    join="left",    # X_train_resampled is the superset
    axis=1,
    fill_value=0
)

Checking the final data

In [38]:
print(X_train_resampled.shape)
print(X_test.shape)

(7760, 30)
(1761, 30)

In [39]:
print(
    set(X_train_resampled.columns) - set(X_test.columns)
)

set()

In [40]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

### LOGISTIC REGRESSION

In [41]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(random_state=42)

lr.fit(X_train_resampled, y_train_resampled)

LogisticRegression(random_state=42)

In [42]:
y_pred = lr.predict(X_test)

In [43]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.750709823963657
Precision: 0.5201149425287356
Recall: 0.7751605995717344
F1: 0.6225279449699054

Confusion Matrix:
[[960 334]
 [105 362]]

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.74      0.81      1294
           1       0.52      0.78      0.62       467

    accuracy                           0.75      1761
   macro avg       0.71      0.76      0.72      1761
weighted avg       0.80      0.75      0.76      1761

### DECISION TREE

In [44]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train_resampled, y_train_resampled)

y_pred_dt = dt.predict(X_test)

In [45]:
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt))
print("Recall:", recall_score(y_test, y_pred_dt))
print("F1:", f1_score(y_test, y_pred_dt))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt))

Accuracy: 0.7348097671777399
Precision: 0.5
Recall: 0.588865096359743
F1: 0.5408062930186824

Confusion Matrix:
[[1019  275]
 [ 192  275]]

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.79      0.81      1294
           1       0.50      0.59      0.54       467

    accuracy                           0.73      1761
   macro avg       0.67      0.69      0.68      1761
weighted avg       0.75      0.73      0.74      1761

In [46]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    random_state=42,
    n_estimators=200,
    n_jobs=-1
)

rf.fit(X_train_resampled, y_train_resampled)

y_pred_rf = rf.predict(X_test)

In [47]:
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1:", f1_score(y_test, y_pred_rf))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

Accuracy: 0.7773992049971608
Precision: 0.5763747454175153
Recall: 0.6059957173447538
F1: 0.5908141962421712

Confusion Matrix:
[[1086  208]
 [ 184  283]]

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.84      0.85      1294
           1       0.58      0.61      0.59       467

    accuracy                           0.78      1761
   macro avg       0.72      0.72      0.72      1761
weighted avg       0.78      0.78      0.78      1761

In [48]:
from sklearn.metrics import roc_auc_score

y_prob_rf = rf.predict_proba(X_test)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, y_prob_rf))

ROC-AUC: 0.8224865877431333

**What 82.25% ROC-AUC means**<br>
If you randomly pick one customer who churned and one who didn't, there's about an 82.25% chance that the model assigns the churner a higher churn probability

### **Observations**

It may look like RF > LR in terms of accuracy<br>

However, one key point that we must not overlook is the *recall* of Churners (1) of both the models, which is significantly higher in LR (~78%) compared to RF (~61%)

### Keeping in mind that ACCURACY is still not being considered a reliable metric

In [49]:
y_prob_lr = lr.predict_proba(X_test)[:, 1]

print("ROC-AUC for LR:", roc_auc_score(y_test, y_prob_lr))

ROC-AUC for LR: 0.8368040271521666

I am also comparing the effect SMOTENC has on the results

In [50]:
X = df.drop("Churn", axis=1)
y = df["Churn"]

X_train_no_smote, X_test_no_smote, y_train_no_smote, y_test_no_smote = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

In [51]:
median = X_train_no_smote["TotalCharges"].median()

X_train_no_smote["TotalCharges"] = X_train_no_smote["TotalCharges"].fillna(median)
X_test_no_smote["TotalCharges"] = X_test_no_smote["TotalCharges"].fillna(median)

In [52]:
scaler_no_smote = StandardScaler()

scaler_no_smote.fit(X_train_no_smote[numerical_cols])

X_train_no_smote[numerical_cols] = scaler_no_smote.transform(
    X_train_no_smote[numerical_cols]
)

X_test_no_smote[numerical_cols] = scaler_no_smote.transform(
    X_test_no_smote[numerical_cols]
)

In [53]:
X_train_no_smote = pd.get_dummies(
    X_train_no_smote,
    columns=categorical_cols,
    drop_first=True
)

X_test_no_smote = pd.get_dummies(
    X_test_no_smote,
    columns=categorical_cols,
    drop_first=True
)

In [54]:
X_train_no_smote, X_test_no_smote = X_train_no_smote.align(
    X_test_no_smote,
    join="left",
    axis=1,
    fill_value=0
)

In [55]:
lr_no_smote = LogisticRegression(random_state=42)

lr_no_smote.fit(
    X_train_no_smote,
    y_train_no_smote
)

y_pred_lr_no_smote = lr_no_smote.predict(X_test_no_smote)
y_prob_lr_no_smote = lr_no_smote.predict_proba(X_test_no_smote)[:, 1]

print("Accuracy :", accuracy_score(y_test, y_pred_lr_no_smote))
print("Precision:", precision_score(y_test, y_pred_lr_no_smote))
print("Recall   :", recall_score(y_test, y_pred_lr_no_smote))
print("F1       :", f1_score(y_test, y_pred_lr_no_smote))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_lr_no_smote))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr_no_smote))

Accuracy : 0.8069278818852924
Precision: 0.6615776081424937
Recall   : 0.556745182012848
F1       : 0.6046511627906976
ROC-AUC  : 0.846540945030432

Confusion Matrix:
[[1161  133]
 [ 207  260]]

In [56]:
rf_no_smote = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf_no_smote.fit(X_train_no_smote, y_train_no_smote)

y_pred_rf_no_smote = rf_no_smote.predict(X_test)
y_prob_rf_no_smote = rf_no_smote.predict_proba(X_test)[:, 1]

print("Accuracy :", accuracy_score(y_test, y_pred_rf_no_smote))
print("Precision:", precision_score(y_test, y_pred_rf_no_smote))
print("Recall   :", recall_score(y_test, y_pred_rf_no_smote))
print("F1       :", f1_score(y_test, y_pred_rf_no_smote))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_rf_no_smote))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf_no_smote))

Accuracy : 0.7898921067575241
Precision: 0.6366197183098592
Recall   : 0.48394004282655245
F1       : 0.5498783454987834
ROC-AUC  : 0.8265648736219546

Confusion Matrix:
[[1165  129]
 [ 241  226]]

We can clearly see that SMOTENC actually has helped in making the recall(most important metric in this case) good<br>

**BEFORE:**<br>
Precision = 66.16%<br>
Recall    = 55.67%<br>
F1        = 60.46%<br>
ROC-AUC   = 84.65%<br>

**AFTER**<br>
Precision = 50.21%  ↓<br>
Recall    = 77.52%  ↑↑<br>
F1        = 62.25%  ↑<br>
ROC-AUC   = 83.68%  ↓<br>

### XGBoost

In [57]:
from xgboost import XGBClassifier

In [58]:
xgb = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(X_train_resampled, y_train_resampled)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [59]:
y_pred_xgb = xgb.predict(X_test)
y_prob_xgb = xgb.predict_proba(X_test)[:, 1]

In [60]:
print("Accuracy :", accuracy_score(y_test, y_pred_xgb))
print("Precision:", precision_score(y_test, y_pred_xgb))
print("Recall   :", recall_score(y_test, y_pred_xgb))
print("F1       :", f1_score(y_test, y_pred_xgb))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_xgb))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

Accuracy : 0.7654741624077229
Precision: 0.5434083601286174
Recall   : 0.7237687366167024
F1       : 0.620752984389348
ROC-AUC  : 0.8381990342513131

Confusion Matrix:
[[1010  284]
 [ 129  338]]

I am also doing experiments with thresholds, changing the threshold might have an impact on the model's performance.

In [61]:
thresholds = np.arange(0.2, 0.61, 0.05)

for threshold in thresholds:
    y_pred_threshold = (y_prob_lr_no_smote >= threshold).astype(int)

    print(
        f"Threshold: {threshold:.2f} | "
        f"Precision: {precision_score(y_test, y_pred_threshold):.3f} | "
        f"Recall: {recall_score(y_test, y_pred_threshold):.3f} | "
        f"F1: {f1_score(y_test, y_pred_threshold):.3f}"
    )

Threshold: 0.20 | Precision: 0.477 | Recall: 0.857 | F1: 0.613
Threshold: 0.25 | Precision: 0.507 | Recall: 0.812 | F1: 0.624
Threshold: 0.30 | Precision: 0.532 | Recall: 0.762 | F1: 0.627
Threshold: 0.35 | Precision: 0.553 | Recall: 0.719 | F1: 0.625
Threshold: 0.40 | Precision: 0.587 | Recall: 0.683 | F1: 0.632
Threshold: 0.45 | Precision: 0.604 | Recall: 0.617 | F1: 0.610
Threshold: 0.50 | Precision: 0.662 | Recall: 0.557 | F1: 0.605
Threshold: 0.55 | Precision: 0.674 | Recall: 0.456 | F1: 0.544
Threshold: 0.60 | Precision: 0.702 | Recall: 0.383 | F1: 0.496

Just focusing on recall doesn't mean we can ignore the other metrics.<br>
So, I am keeping the cutoff of recall to atleast 75%, and then experimenting with different thresholds to see which threshold gives the best precision for >75% recall.

In [62]:
thresholds = np.arange(0.01, 0.51, 0.001)

results = []

for threshold in thresholds:
    y_pred = (y_prob_lr_no_smote >= threshold).astype(int)

    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    results.append({
        'threshold': threshold,
        "precision": precision,
        "recall": recall,
        "f1": f1
    })

threshold_df = pd.DataFrame(results)

best = (
    threshold_df[threshold_df['recall'] >= 0.75].sort_values('precision', ascending=False).iloc[0]
)

print(best)

threshold    0.312000
precision    0.539171
recall       0.751606
f1           0.627907
Name: 302, dtype: float64

## For now, I am serving the LR with SMOTE model (lr)

In [63]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('lr', lr)
])

In [64]:
pipeline.fit(X_train_resampled, y_train_resampled)

Pipeline(steps=[('lr', LogisticRegression(random_state=42))])

In [65]:
import pickle

pickle.dump(pipeline, open('LogisticRegressionChurn.pkl', 'wb'))

#### Saving the model and preprocessing stuff

In [66]:
import joblib

joblib.dump(lr, 'LogRegression.pkl')

# scaler
joblib.dump(scaler, 'scaler.pkl')

# median to impute TotalCharges
joblib.dump(median, 'TC_median.pkl')

joblib.dump(X_train_resampled.columns.tolist(),
            'feature_columns.pkl'
            )

['feature_columns.pkl']